quarkus.zeebe.client.cloud.client-id=
quarkus.zeebe.client.cloud.client-secret=
quarkus.zeebe.client.cloud.cluster-id=
quarkus.zeebe.client.cloud.region=

quarkus.zeebe.client.security.plaintext=false
quarkus.zeebe.devservices.enabled=false